name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.1
            gemfile: gems/rails3.gemfile
          - ruby: 2.2
          - ruby: 2.3
          - ruby: 2.4
          - ruby: 2.5
          - ruby: 2.6
          - ruby: 2.6
            gemfile: gems/octoshark.gemfile
          - ruby: 2.6
            gemfile: gems/rails3.gemfile
            bundler: 1.17.3
          - ruby: 2.7
          - ruby: 3.0

          #- ruby: 2.6
          #  name: rubocop yo
          #  script: bundle exec rubocop

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: ${{matrix.bundler}}
          ruby-version: ${{ matrix.ruby }}
      - run: bundle exec rake
